name: Publish Python Package

on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine toml

      - name: Update version from tag
        if: github.ref_type == 'tag'
        run: |
          echo "Tag detected: $GITHUB_REF_NAME"
          # Strip leading 'v' if present, otherwise keep tag as-is
          VERSION=${GITHUB_REF_NAME#v}
          echo "Updating pyproject.toml version to $VERSION"
          python - <<EOF
          import toml
          from pathlib import Path
          path = Path("pyproject.toml")
          data = toml.load(path)
          data["project"]["version"] = "$VERSION"
          toml.dump(data, path.open("w"))
          EOF

      - name: Clean old builds
        run: rm -rf dist build *.egg-info

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/* --verbose
